import React, { createContext, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
    EN: {
        nav_analyze: "Analyze Crop",
        nav_history: "My History",
        nav_signin: "Sign In",

        hero_title_1: "Farming",
        hero_title_2: "Reimagined",
        hero_subtitle: "Detect crop diseases instantly with AI and get personalized fertilizer recommendations tailored to your soil.",
        footer: "© 2026 AgriAid AI Systems. Built for Indian Farmers.",

        // Login Page
        login_welcome: "Welcome Back",
        login_subtitle: "Sign in to access your farm dashboard",
        login_email: "Email Address",
        login_password: "Password",
        login_btn: "Sign In",
        login_forgot: "Forgot Password?",
        login_no_account: "Don't have an account?",
        login_signup: "Sign Up",
        login_logging_in: "Logging in...",
        nav_logout: "Log Out",
        nav_profile: "My Profile",
        nav_dashboard: "Dashboard",
        nav_settings: "Settings",
        nav_help: "Help & Support",
        nav_alerts: "Weather Alerts",
        nav_tools: "Tools",
        nav_simulators: "Simulators",
        nav_farmer_tools: "Farmer Tools",
        nav_advanced_sims: "Advanced Simulations",
        nav_crop_calendar: "Crop Calendar",
        nav_fert_calc: "Fertilizer Calc",
        nav_weather_forecast: "Weather Forecast",
        nav_market_prices: "Market Prices",
        nav_soil_health: "Soil Health Check",
        nav_impact_sim: "Impact Simulator",
        nav_future_growth: "Future Growth Sim",
        nav_disease_spread: "Disease Spread Sim",
        nav_farming_timeline: "Farming Timeline",

        soil_alluvial: "Alluvial",
        soil_red_soil: "Red Soil",
        soil_black_soil: "Black Soil",
        soil_laterite: "Laterite",
        soil_desert_soil: "Desert Soil",

        // Impact Simulator
        impact_title: "ImpactSim",
        impact_subtitle: "Compare Organic vs Chemical Farming Outcomes",
        impact_parameters: "Parameters",
        impact_target_crop: "TARGET CROP",
        impact_soil_profile: "SOIL PROFILE",
        impact_area: "AREA (ACRES)",
        impact_cycle: "CYCLE (MO)",
        impact_intensity: "INPUT INTENSITY",
        impact_low: "LOW",
        impact_medium: "MEDIUM",
        impact_high: "HIGH",
        impact_run_sim: "Run Simulation",
        impact_simulating: "Simulating...",
        impact_organic_protocol: "Organic Protocol",
        impact_safe_yield: "Safe Yield",
        impact_chemical_protocol: "Chemical Protocol",
        impact_high_risk: "High Risk",
        impact_est_yield: "Est. Yield",
        impact_proj_profit: "Proj. Profit",
        impact_soil_health: "Soil Health",
        impact_yield_journey: "Yield Prediction Journey",
        impact_ai_insight: "AI Executive Insight",
        impact_listen: "Listen",
        impact_stop: "Stop",
        impact_ws_title: "Impact Analysis Workspace",
        impact_ws_awaiting: "Awaiting configuration",
        impact_ws_ready: "Ready for Simulation",
        impact_ws_desc: "Adjust crop and farming parameters in the left panel to compare organic and chemical outcomes.",
        impact_ws_step1: "Inputs",
        impact_ws_step1_desc: "Set crop & area",
        impact_ws_step2: "Simulate",
        impact_ws_step2_desc: "Run AI model",
        impact_ws_step3: "Compare",
        impact_ws_step3_desc: "Review yields",

        // Smart Farming Timeline
        timeline_title: "Smart Farming Timeline",
        timeline_subtitle: "AI-Generated cultivation schedule & milestones",
        timeline_parameters: "Cultivation Details",
        timeline_generate_btn: "Generate Timeline",
        timeline_preview_title: "Timeline Preview",
        timeline_preview_placeholder: "Enter details to preview cultivation schedule",
        timeline_crop: "Crop Species",
        timeline_start_date: "Sowing Date",
        timeline_deployment_params: "Deployment Params",
        timeline_active_phase: "Active Phase",
        timeline_pathogen_alert: "Pathogen Alert",
        timeline_critical_risk: "Critical Risk: Soil treatment",
        timeline_economic_insight: "Economic Insight",
        timeline_yield_confidence: "Yield Confidence",
        timeline_water_intensity: "Water Intensity",

        // Crop Calendar
        cal_badge: "AI Precision Scheduler",
        cal_title: "Crop Calendar",
        cal_subtitle: "AI-powered lifecycle planner with real-time weather, soil & market intelligence.",
        cal_search_placeholder: "Search any crop... (e.g. Rice, Tomato, Ri...)",
        cal_search_label: "Search Crop",
        cal_date_label: "Sowing Date",
        cal_location_label: "Location",
        cal_location_detecting: "Detecting location...",
        cal_location_edit: "Edit location",
        cal_location_hide: "Hide",
        cal_state_placeholder: "State (e.g. Tamil Nadu)",
        cal_district_placeholder: "District (e.g. Madurai)",
        cal_generate_btn: "Generate AI Calendar",
        cal_generating: "AI is building your calendar...",
        cal_empty_title: "Ready to Plan Your Season",
        cal_empty_desc: "Search a crop and set your sowing date to get a complete AI-powered farming calendar.",
        cal_step1: "Search Crop",
        cal_step1_desc: "Type any crop name",
        cal_step2: "Set Date",
        cal_step2_desc: "Pick sowing date",
        cal_step3: "Get Calendar",
        cal_step3_desc: "AI builds your plan",
        cal_yield_conf: "Yield Confidence",
        cal_water: "Water Intensity",
        cal_season: "Season",
        cal_duration: "Duration",
        cal_days: "days",
        cal_harvest_window: "Harvest Window",
        cal_early: "Early",
        cal_optimal: "Optimal",
        cal_late: "Late",
        cal_soil_req: "Soil Requirements",
        cal_market: "Market Outlook",
        cal_warnings: "Critical Warnings",
        cal_ai_summary: "AI Expert Summary",
        cal_active_phase: "Active Phase",
        cal_weather_adj: "Weather Advisory",
        cal_irrigation: "Irrigation",
        cal_fertilizer: "Fertilizer",
        cal_pest_risk: "Pest / Disease Risk",
        cal_economic: "Economic Insight",
        cal_risk_high: "High Risk",
        cal_risk_medium: "Medium Risk",
        cal_risk_low: "Low Risk",
        cal_no_results: "No crops found. Try a different name.",
        cal_ai_searching: "AI searching...",
        cal_location_locked: "Location locked",
        cal_location_syncing: "Syncing GPS...",

        // Help & Support
        help_subtitle: "We are here to help you with any questions.",
        help_call: "Call Support",
        help_call_desc: "Mon-Fri, 9AM - 6PM",
        help_email: "Email Us",
        help_email_desc: "We reply within 24 hours",
        help_faq_title: "Frequently Asked Questions",

        faq_q1: "How do I scan a crop?",
        faq_a1: "Go to the Dashboard, click on 'Crop Analyzer', and upload or take a photo of your crop leaf. The AI will analyze it instantly.",
        faq_q2: "Is the fertilizer recommendation accurate?",
        faq_a2: "Our recommendations are based on standard agricultural data and ML models. However, we always recommend consulting a local expert for critical decisions.",
        faq_q3: "How can I change the app language?",
        faq_a3: "Go to Settings > Language and select your preferred language (English, Hindi, or Tamil).",
        faq_q4: "What if the app is not loading?",
        faq_a4: "Check your internet connection using the built-in Connection Status tool in Settings. If the issue persists, try clearing your browser cache.",

        // Settings Page
        settings_subtitle: "Manage your preferences and app configuration.",
        settings_language: "Language",
        settings_general: "General Preferences",
        settings_notifications: "Push Notifications",
        settings_notifications_desc: "Receive alerts about weather and crop health.",
        settings_darkmode: "Dark Mode",
        settings_darkmode_desc: "Switch to a darker theme for night usage.",
        settings_datasaver: "Data Saver",
        settings_datasaver_desc: "Reduce image quality to save mobile data.",

        nav_welcome_user: "Hello,",

        // Signup Page
        signup_title: "Create Account",
        signup_subtitle: "Join the smart farming community",
        signup_name: "Full Name",
        signup_confirm_password: "Confirm Password",
        signup_btn: "Create Account",
        signup_have_account: "Already have an account?",
        signup_login: "Sign In",
        signup_creating: "Creating Account...",

        // Profile Page
        profile_title: "My Farmer Profile",
        profile_details: "Personal Details",
        profile_name: "Full Name",
        profile_email: "Email Address",
        profile_phone: "Phone Number",
        profile_location: "Farm Location",
        profile_save: "Save Changes",
        profile_stat_scans: "Total Scans",
        profile_stat_healthy: "Healthy Crops",
        profile_stat_issues: "Issues Detected",

        crop_details: "Crop Details",
        select_crop: "Select Crop",
        district: "District",
        state: "State",

        // Crops
        crop_rice: "Rice",
        crop_wheat: "Wheat",
        crop_corn: "Corn",
        crop_potato: "Potato",
        crop_tomato: "Tomato",
        crop_grape: "Grape",
        crop_chilli: "Chilli",
        crop_brinjal: "Brinjal",
        crop_spinach: "Spinach",
        crop_coriander: "Coriander",
        crop_mint: "Mint",
        crop_capsicum: "Capsicum",
        crop_cotton: "Cotton",
        crop_sugarcane: "Sugarcane",
        crop_maize: "Maize",
        crop_groundnut: "Groundnut",
        crop_banana: "Banana",
        crop_cashew: "Cashew",

        // States
        state_mh: "Maharashtra",
        state_pb: "Punjab",
        state_ka: "Karnataka",
        state_tn: "Tamil Nadu",
        state_up: "Uttar Pradesh",
        state_kl: "Kerala",

        upload_title: "Upload Leaf Image",
        upload_subtitle: "Click to upload",
        use_camera: "Use Camera",
        change_photo: "Change Photo",

        analyze_btn: "Analyze Disease",
        analyzing: "Analyzing...",
        analyze_another: "Analyze Another Crop",

        ai_diag_title: "AI-Powered Diagnosis",
        ai_diag_desc: "Upload a photo to get instant insights.",

        feat_visual_title: "Visual Recognition",
        feat_visual_desc: "Advanced CNN models detect diseases like Blight, Rust, and Blast with high accuracy.",

        feat_remedy_title: "Smart Remedies",
        feat_remedy_desc: "Get precise fertilizer dosages (e.g. Hexaconazole, Tricyclazole) tailored to your crop.",

        feat_alert_title: "Localized Alerts",
        feat_alert_desc: "Recommendations adapted to your selected District and current weather conditions.",

        result_condition: "Detected Condition",
        result_confidence: "Confidence Score",
        result_low_conf: "Low Confidence - Verify Manually",

        rec_title: "Smart Recommendation",
        rec_fertilizer: "Fertilizer",
        rec_dosage: "Dosage",
        rec_instructions: "Instructions",
        weather_alert: "Weather Alert",

        // Diseases
        disease_leaf_blight: "Leaf Blight",
        disease_rust: "Rust",
        disease_mosaic: "Mosaic Virus",
        disease_powdery_mildew: "Powdery Mildew",
        disease_healthy: "Healthy",
        disease_rice_blast: "Rice Blast",
        disease_unknown: "Unknown Classification",

        // Recommendations (Fertilizer, Dosage, Instructions)
        rec_leaf_blight_fert: "Fungicide (Hexaconazole 5% SC)",
        rec_leaf_blight_dose: "2 ml/liter water",
        rec_leaf_blight_inst: "Spray fungicide immediately. Repeat after 15 days if symptoms persist. Add Potash boost to strengthen the plant.",

        rec_rust_fert: "Sulphur Dust / Mancozeb",
        rec_rust_dose: "25 kg/acre (Dust) or 2.5g/liter",
        rec_rust_inst: "Dust sulphur in early morning. Limit Urea application to prevent fungal spread. Ensure good air circulation.",

        rec_mosaic_fert: "Imidacloprid (Vector Control)",
        rec_mosaic_dose: "100ml / acre",
        rec_mosaic_inst: "This is a viral disease spread by aphids. Control the vector. Uproot and destroy infected plants immediately.",

        rec_powdery_mildew_fert: "Wettable Sulphur / Neem Oil",
        rec_powdery_mildew_dose: "2g/liter water",
        rec_powdery_mildew_inst: "Spray organic Neem oil weekly or use sulphur-based fungicides. Improve air circulation and reduce shade.",

        rec_healthy_fert: "Organic Compost / Vermicompost",
        rec_healthy_dose: "500 kg/acre",
        rec_healthy_inst: "Crop is healthy! Maintain soil health. Continue regular irrigation and monitoring.",

        rec_rice_blast_fert: "Tricyclazole / Isoprothiolane",
        rec_rice_blast_dose: "120g/acre",
        rec_rice_blast_inst: "Crucial for Rice. Apply Tricyclazole 75 WP immediately. Maintain standing water in paddy fields to suppress the fungus.",

        rec_default_fert: "Balanced NPK (19:19:19)",
        rec_default_dose: "5 kg/acre (Foliar)",
        rec_default_inst: "Spray to resolve general nutrient deficiencies and boost immunity.",

        // New Diseases (Generic Fallbacks for complex keys)
        disease_cotton_fussarium_wilt: "Cotton Fusarium Wilt",
        rec_cotton_fussarium_wilt_fert: "Trichoderma viride / Pseudomonas",
        rec_cotton_fussarium_wilt_dose: "2 kg/acre (Soil Drenching)",
        rec_cotton_fussarium_wilt_inst: "Drench root zone. Stop irrigation immediately if fungal wilt is suspected.",

        disease_banana_sigatoka: "Banana Sigatoka (Leaf Spot)",
        rec_banana_sigatoka_fert: "Propiconazole / Difenoconazole",
        rec_banana_sigatoka_dose: "1 ml/liter",
        rec_banana_sigatoka_inst: "Critical for Banana. Alternating fungicides prevents resistance. Remove infected leaves.",

        disease_banana_cordana: "Banana Cordana Leaf Spot",
        rec_banana_cordana_fert: "Copper Oxychloride / Mancozeb",
        rec_banana_cordana_dose: "2.5 g/liter",
        rec_banana_cordana_inst: "Remove infected leaves. Improve drainage and reduce humidity around the plant.",

        disease_banana_pestalotiopsis: "Banana Pestalotiopsis",
        rec_banana_pestalotiopsis_fert: "Carbendazim / Thiophanate Methyl",
        rec_banana_pestalotiopsis_dose: "1 g/liter",
        rec_banana_pestalotiopsis_inst: "Spray fungicides if infection is severe. Maintain field hygiene.",

        disease_banana_healthy: "Healthy Banana",
        rec_banana_healthy_fert: "Organic Compost / Vermicompost",
        rec_banana_healthy_dose: "2 kg/plant",
        rec_banana_healthy_inst: "The plant is healthy! Continue regular irrigation and apply organic manure to maintain soil fertility.",

        disease_maize_common_rust: "Maize Common Rust",
        rec_maize_common_rust_fert: "Mancozeb / Sulphur",
        rec_maize_common_rust_dose: "2.5 g/liter",
        rec_maize_common_rust_inst: "Apply fungicide when pustules appear. Plant resistant hybrids if possible.",

        disease_sugarcane_redrot: "Sugarcane Red Rot",
        rec_sugarcane_redrot_fert: "Carbendazim (0.1%)",
        rec_sugarcane_redrot_dose: "Seed Treatment",
        rec_sugarcane_redrot_inst: "Destroy infected canes. Use resistant varieties. Do not reuse seeds from infected fields.",

        disease_wheat_septoria: "Wheat Septoria",
        rec_wheat_septoria_fert: "Azoxystrobin / Epoxiconazole",
        rec_wheat_septoria_dose: "500 ml/acre",
        rec_wheat_septoria_inst: "Apply at flag leaf stage. Ensure proper rotation.",

        // Dynamic sentence parts
        rec_for: "For",
        rec_in: "in",

        weather_optimal: "Optimal conditions for fertilizer application.",

        // Chatbot
        chat_button: "Chatbot",
        chat_title: "Farmer Assistant",
        chat_status: "Online",
        chat_placeholder: "Ask about crops, diseases...",

        // Soil Health
        soil_health: "Soil Health Data",
        soil_advanced: "Advanced",
        soil_n: "Nitrogen (N)",
        soil_p: "Phosphorus (P)",
        soil_k: "Potassium (K)",

        // Insights
        insight_title: "Live Farming Insights",
        insight_weather: "Weather Widget",
        insight_market: "Market Price",
        insight_per_quintal: "per Quintal",
        insight_good_spray: "Good for Spraying",

        // History
        hist_title: "Analysis History",
        hist_subtitle: "Track your past crop diagnoses and recommendations.",
        hist_empty: "No history found. Start by analyzing a crop!",
        hist_btn_details: "View Details",
        hist_delete: "Delete Record",

        // Farming Types
        type_home: "Home Gardening",
        type_commercial: "Commercial Farming",

        // Districts - Tamil Nadu
        dist_ariyalur: "Ariyalur",
        dist_chengalpattu: "Chengalpattu",
        dist_chennai: "Chennai",
        dist_coimbatore: "Coimbatore",
        dist_cuddalore: "Cuddalore",
        dist_dharmapuri: "Dharmapuri",
        dist_dindigul: "Dindigul",
        dist_erode: "Erode",
        dist_kallakurichi: "Kallakurichi",
        dist_kancheepuram: "Kancheepuram",
        dist_kanniyakumari: "Kanniyakumari",
        dist_karur: "Karur",
        dist_krishnagiri: "Krishnagiri",
        dist_madurai: "Madurai",
        dist_mayiladuthurai: "Mayiladuthurai",
        dist_nagapattinam: "Nagapattinam",
        dist_namakkal: "Namakkal",
        dist_nilgiris: "Nilgiris",
        dist_perambalur: "Perambalur",
        dist_pudukkottai: "Pudukkottai",
        dist_ramanathapuram: "Ramanathapuram",
        dist_ranipet: "Ranipet",
        dist_salem: "Salem",
        dist_sivagangai: "Sivagangai",
        dist_tenkasi: "Tenkasi",
        dist_thanjavur: "Thanjavur",
        dist_theni: "Theni",
        dist_thiruvallur: "Thiruvallur",
        dist_thiruvarur: "Thiruvarur",
        dist_thoothukudi: "Thoothukudi",
        dist_tiruchirappalli: "Tiruchirappalli",
        dist_tirunelveli: "Tirunelveli",
        dist_tirupathur: "Tirupathur",
        dist_tiruppur: "Tiruppur",
        dist_tiruvannamalai: "Tiruvannamalai",
        dist_vellore: "Vellore",
        dist_viluppuram: "Viluppuram",
        dist_virudhunagar: "Virudhunagar",

        // Districts - Maharashtra
        dist_ahmednagar: "Ahmednagar",
        dist_akola: "Akola",
        dist_amravati: "Amravati",
        dist_aurangabad: "Aurangabad",
        dist_beed: "Beed",
        dist_bhandara: "Bhandara",
        dist_buldhana: "Buldhana",
        dist_chandrapur: "Chandrapur",
        dist_dhule: "Dhule",
        dist_gadchiroli: "Gadchiroli",
        dist_gondia: "Gondia",
        dist_hingoli: "Hingoli",
        dist_jalgaon: "Jalgaon",
        dist_jalna: "Jalna",
        dist_kolhapur: "Kolhapur",
        dist_latur: "Latur",
        dist_mumbai_city: "Mumbai City",
        dist_mumbai_suburban: "Mumbai Suburban",
        dist_nagpur: "Nagpur",
        dist_nanded: "Nanded",
        dist_nandurbar: "Nandurbar",
        dist_nashik: "Nashik",
        dist_osmanabad: "Osmanabad",
        dist_palghar: "Palghar",
        dist_parbhani: "Parbhani",
        dist_pune: "Pune",
        dist_raigad: "Raigad",
        dist_ratnagiri: "Ratnagiri",
        dist_sangli: "Sangli",
        dist_satara: "Satara",
        dist_sindhudurg: "Sindhudurg",
        dist_solapur: "Solapur",
        dist_thane: "Thane",
        dist_wardha: "Wardha",
        dist_washim: "Washim",
        dist_yavatmal: "Yavatmal",

        // Districts - Punjab
        dist_amritsar: "Amritsar",
        dist_barnala: "Barnala",
        dist_bathinda: "Bathinda",
        dist_faridkot: "Faridkot",
        dist_fatehgarh_sahib: "Fatehgarh Sahib",
        dist_fazilka: "Fazilka",
        dist_ferozepur: "Ferozepur",
        dist_gurdaspur: "Gurdaspur",
        dist_hoshiarpur: "Hoshiarpur",
        dist_jalandhar: "Jalandhar",
        dist_kapurthala: "Kapurthala",
        dist_ludhiana: "Ludhiana",
        dist_mansa: "Mansa",
        dist_moga: "Moga",
        dist_mohali_sas_nagar: "Mohali (SAS Nagar)",
        dist_muktsar: "Muktsar",
        dist_nawanshahr_sbs_nagar: "Nawanshahr (SBS Nagar)",
        dist_pathankot: "Pathankot",
        dist_patiala: "Patiala",
        dist_ropar_rupnagar: "Ropar (Rupnagar)",
        dist_sangrur: "Sangrur",
        dist_tarn_taran: "Tarn Taran",

        // Districts - Karnataka
        dist_bagalkot: "Bagalkot",
        dist_bangalore_rural: "Bangalore Rural",
        dist_bangalore_urban: "Bangalore Urban",
        dist_belgaum: "Belgaum",
        dist_bellary: "Bellary",
        dist_bidar: "Bidar",
        dist_chamarajanagar: "Chamarajanagar",
        dist_chikkaballapur: "Chikkaballapur",
        dist_chikkamagaluru: "Chikkamagaluru",
        dist_chitradurga: "Chitradurga",
        dist_dakshina_kannada: "Dakshina Kannada",
        dist_davangere: "Davangere",
        dist_dharwad: "Dharwad",
        dist_gadag: "Gadag",
        dist_gulbarga: "Gulbarga",
        dist_hassan: "Hassan",
        dist_haveri: "Haveri",
        dist_kodagu: "Kodagu",
        dist_kolar: "Kolar",
        dist_koppal: "Koppal",
        dist_mandya: "Mandya",
        dist_mysore: "Mysore",
        dist_raichur: "Raichur",
        dist_ramanagara: "Ramanagara",
        dist_shimoga: "Shimoga",
        dist_tumkur: "Tumkur",
        dist_udupi: "Udupi",
        dist_uttara_kannada: "Uttara Kannada",
        dist_vijayapura: "Vijayapura",
        dist_yadgir: "Yadgir",

        // Districts - Kerala
        dist_alappuzha: "Alappuzha",
        dist_ernakulam: "Ernakulam",
        dist_idukki: "Idukki",
        dist_kannur: "Kannur",
        dist_kasaragod: "Kasaragod",
        dist_kollam: "Kollam",
        dist_kottayam: "Kottayam",
        dist_kozhikode: "Kozhikode",
        dist_malappuram: "Malappuram",
        dist_palakkad: "Palakkad",
        dist_pathanamthitta: "Pathanamthitta",
        dist_thiruvananthapuram: "Thiruvananthapuram",
        dist_thrissur: "Thrissur",
        dist_wayanad: "Wayanad",

        // Districts - Uttar Pradesh
        dist_agra: "Agra",
        dist_aligarh: "Aligarh",
        dist_ambedkar_nagar: "Ambedkar Nagar",
        dist_amethi: "Amethi",
        dist_amroha: "Amroha",
        dist_auraiya: "Auraiya",
        dist_ayodhya: "Ayodhya",
        dist_azamgarh: "Azamgarh",
        dist_baghpat: "Baghpat",
        dist_bahraich: "Bahraich",
        dist_ballia: "Ballia",
        dist_balrampur: "Balrampur",
        dist_banda: "Banda",
        dist_barabanki: "Barabanki",
        dist_bareilly: "Bareilly",
        dist_basti: "Basti",
        dist_bhadohi: "Bhadohi",
        dist_bijnor: "Bijnor",
        dist_budaun: "Budaun",
        dist_bulandshahr: "Bulandshahr",
        dist_chandauli: "Chandauli",
        dist_chitrakoot: "Chitrakoot",
        dist_deoria: "Deoria",
        dist_etah: "Etah",
        dist_etawah: "Etawah",
        dist_farrukhabad: "Farrukhabad",
        dist_fatehpur: "Fatehpur",
        dist_firozabad: "Firozabad",
        dist_gautam_buddha_nagar_noida: "Gautam Buddha Nagar (Noida)",
        dist_ghaziabad: "Ghaziabad",
        dist_ghazipur: "Ghazipur",
        dist_gonda: "Gonda",
        dist_gorakhpur: "Gorakhpur",
        dist_hamirpur: "Hamirpur",
        dist_hapur: "Hapur",
        dist_hardoi: "Hardoi",
        dist_hathras: "Hathras",
        dist_jalaun: "Jalaun",
        dist_jaunpur: "Jaunpur",
        dist_jhansi: "Jhansi",
        dist_kannauj: "Kannauj",
        dist_kanpur_dehat: "Kanpur Dehat",
        dist_kanpur_nagar: "Kanpur Nagar",
        dist_kasganj: "Kasganj",
        dist_kaushambi: "Kaushambi",
        dist_kheri: "Kheri",
        dist_kushinagar: "Kushinagar",
        dist_lalitpur: "Lalitpur",
        dist_lucknow: "Lucknow",
        dist_maharajganj: "Maharajganj",
        dist_mahoba: "Mahoba",
        dist_mainpuri: "Mainpuri",
        dist_mathura: "Mathura",
        dist_mau: "Mau",
        dist_meerut: "Meerut",
        dist_mirzapur: "Mirzapur",
        dist_moradabad: "Moradabad",
        dist_muzaffarnagar: "Muzaffarnagar",
        dist_pilibhit: "Pilibhit",
        dist_pratapgarh: "Pratapgarh",
        dist_prayagraj_allahabad: "Prayagraj (Allahabad)",
        dist_raebareli: "Raebareli",
        dist_rampur: "Rampur",
        dist_saharanpur: "Saharanpur",
        dist_sambhal: "Sambhal",
        dist_sant_kabir_nagar: "Sant Kabir Nagar",
        dist_shahjahanpur: "Shahjahanpur",
        dist_shamli: "Shamli",
        dist_shravasti: "Shravasti",
        dist_siddharthnagar: "Siddharthnagar",
        dist_sitapur: "Sitapur",
        dist_sonbhadra: "Sonbhadra",
        dist_sultanpur: "Sultanpur",
        dist_unnao: "Unnao",
        dist_varanasi: "Varanasi"
    },
    HI: {
        nav_analyze: "फसल विश्लेषण",
        nav_history: "मेरा इतिहास",
        nav_signin: "साइन इन करें",

        hero_title_1: "स्मार्ट खेती",
        hero_title_2: "क्रांति",
        hero_subtitle: "AI के साथ फसल रोगों का तुरंत पता लगाएं और अपनी मिट्टी के अनुकूल उर्वरक सिफारिशें प्राप्त करें।",
        footer: "© 2026 एग्रीक्योर एआई सिस्टम्स। भारतीय किसानों के लिए निर्मित।",

        // Login Page
        login_welcome: "वापसी पर स्वागत है",
        login_subtitle: "अपने फ़ार्म डैशबोर्ड तक पहुँचने के लिए साइन इन करें",
        login_email: "ईमेल पता",
        login_password: "पासवर्ड",
        login_btn: "साइन इन करें",
        login_forgot: "पासवर्ड भूल गए?",
        login_no_account: "खाता नहीं है?",
        login_signup: "साइन अप करें",
        login_logging_in: "लॉगिन हो रहा है...",
        nav_logout: "लॉग आउट",
        nav_profile: "मेरी रूपरेखा",
        nav_dashboard: "डैशबोर्ड",
        nav_settings: "सेटिंग्स",
        nav_help: "सहायता और समर्थन",
        nav_alerts: "मौसम अलर्ट",
        nav_tools: "उपकरण",
        nav_simulators: "सिम्युलेटर",
        nav_farmer_tools: "किसान उपकरण",
        nav_advanced_sims: "उन्नत सिमुलेशन",
        nav_crop_calendar: "फसल कैलेंडर",
        nav_fert_calc: "उर्वरक कैलकुलेटर",
        nav_weather_forecast: "मौसम पूर्वानुमान",
        nav_market_prices: "बाजार मूल्य",
        nav_soil_health: "मिट्टी स्वास्थ्य जांच",
        nav_impact_sim: "प्रभाव सिम्युलेटर",
        nav_future_growth: "भविष्य के विकास सिम्युलेटर",
        nav_disease_spread: "रोग प्रसार सिम्युलेटर",
        nav_farming_timeline: "खेती समयरेखा",

        soil_alluvial: "जलोढ़ मिट्टी",
        soil_red_soil: "लाल मिट्टी",
        soil_black_soil: "काली मिट्टी",
        soil_laterite: "लेटराइट मिट्टी",
        soil_desert_soil: "रेगिस्तानी मिट्टी",

        // Impact Simulator
        impact_title: "इम्पैक्टसिम",
        impact_subtitle: "जैविक बनाम रासायनिक खेती परिणामों की तुलना करें",
        impact_parameters: "मापदंड",
        impact_target_crop: "लक्षित फसल",
        impact_soil_profile: "मिट्टी का प्रकार",
        impact_area: "क्षेत्र (एकड़)",
        impact_cycle: "चक्र (महीने)",
        impact_intensity: "इनपुट तीव्रता",
        impact_low: "कम",
        impact_medium: "मध्यम",
        impact_high: "अधिक",
        impact_run_sim: "सिमुलेशन चलाएं",
        impact_simulating: "सिम्युलेटिंग...",
        impact_organic_protocol: "जैविक प्रोटोकॉल",
        impact_safe_yield: "सुरक्षित उपज",
        impact_chemical_protocol: "रासायनिक प्रोटोकॉल",
        impact_high_risk: "उच्च जोखिम",
        impact_est_yield: "अनुमानित उपज",
        impact_proj_profit: "अनुमानित लाभ",
        impact_soil_health: "मिट्टी का स्वास्थ्य",
        impact_yield_journey: "उपज भविष्यवाणी यात्रा",
        impact_ai_insight: "AI कार्यकारी अंतर्दृष्टि",
        impact_listen: "सुनें",
        impact_stop: "रोकें",
        impact_ws_title: "प्रभाव विश्लेषण कार्यक्षेत्र",
        impact_ws_awaiting: "कॉन्फ़िगरेशन की प्रतीक्षा में",
        impact_ws_ready: "सिमुलेशन के लिए तैयार",
        impact_ws_desc: "जैविक और रासायनिक परिणामों की तुलना करने के लिए बाएं पैनल में फसल और खेती के मापदंडों को समायोजित करें।",
        impact_ws_step1: "इनपुट",
        impact_ws_step1_desc: "फसल और क्षेत्र सेट करें",
        impact_ws_step2: "सिम्युलेट",
        impact_ws_step2_desc: "AI मॉडल चलाएं",
        impact_ws_step3: "तुलना करें",
        impact_ws_step3_desc: "उपज की समीक्षा करें",

        // Smart Farming Timeline
        timeline_title: "स्मार्ट खेती समयरेखा",
        timeline_subtitle: "AI-जनित खेती अनुसूची और मील के पत्थर",
        timeline_parameters: "खेती का विवरण",
        timeline_generate_btn: "समयरेखा उत्पन्न करें",
        timeline_preview_title: "समयरेखा पूर्वावलोकन",
        timeline_preview_placeholder: "खेती कार्यक्रम का पूर्वावलोकन करने के लिए विवरण दर्ज करें",
        timeline_crop: "फसल की प्रजाति",
        timeline_start_date: "बुवाई की तारीख",
        timeline_deployment_params: "परिनियोजन पैरामीटर",
        timeline_active_phase: "सक्रिय चरण",
        timeline_pathogen_alert: "रोगजनक अलर्ट",
        timeline_critical_risk: "गंभीर जोखिम: मृदा उपचार",
        timeline_economic_insight: "आर्थिक अंतर्दृष्टि",
        timeline_yield_confidence: "उपज का विश्वास",
        timeline_water_intensity: "पानी की तीव्रता",

        // Crop Calendar
        cal_badge: "AI सटीक शेड्यूलर",
        cal_title: "फसल कैलेंडर",
        cal_subtitle: "रियल-टाइम मौसम, मिट्टी और बाजार बुद्धिमत्ता के साथ AI-संचालित जीवनचक्र योजनाकार।",
        cal_search_placeholder: "कोई भी फसल खोजें... (जैसे चावल, टमाटर, च...)",
        cal_search_label: "फसल खोजें",
        cal_date_label: "बुवाई की तारीख",
        cal_location_label: "स्थान",
        cal_location_detecting: "स्थान का पता लगाया जा रहा है...",
        cal_location_edit: "स्थान संपादित करें",
        cal_location_hide: "छुपाएं",
        cal_state_placeholder: "राज्य (जैसे तमिलनाडु)",
        cal_district_placeholder: "जिला (जैसे मदुरै)",
        cal_generate_btn: "AI कैलेंडर बनाएं",
        cal_generating: "AI आपका कैलेंडर बना रहा है...",
        cal_empty_title: "अपना सीजन प्लान करने के लिए तैयार",
        cal_empty_desc: "पूर्ण AI-संचालित खेती कैलेंडर पाने के लिए फसल खोजें और बुवाई की तारीख सेट करें।",
        cal_step1: "फसल खोजें",
        cal_step1_desc: "कोई भी फसल का नाम टाइप करें",
        cal_step2: "तारीख सेट करें",
        cal_step2_desc: "बुवाई की तारीख चुनें",
        cal_step3: "कैलेंडर पाएं",
        cal_step3_desc: "AI आपकी योजना बनाता है",
        cal_yield_conf: "उपज का विश्वास",
        cal_water: "पानी की तीव्रता",
        cal_season: "मौसम",
        cal_duration: "अवधि",
        cal_days: "दिन",
        cal_harvest_window: "कटाई की खिड़की",
        cal_early: "जल्दी",
        cal_optimal: "इष्टतम",
        cal_late: "देर से",
        cal_soil_req: "मिट्टी की आवश्यकताएं",
        cal_market: "बाजार दृष्टिकोण",
        cal_warnings: "महत्वपूर्ण चेतावनियां",
        cal_ai_summary: "AI विशेषज्ञ सारांश",
        cal_active_phase: "सक्रिय चरण",
        cal_weather_adj: "मौसम सलाह",
        cal_irrigation: "सिंचाई",
        cal_fertilizer: "उर्वरक",
        cal_pest_risk: "कीट / रोग जोखिम",
        cal_economic: "आर्थिक अंतर्दृष्टि",
        cal_risk_high: "उच्च जोखिम",
        cal_risk_medium: "मध्यम जोखिम",
        cal_risk_low: "कम जोखिम",
        cal_no_results: "कोई फसल नहीं मिली। कोई अलग नाम आज़माएं।",
        cal_ai_searching: "AI खोज रहा है...",
        cal_location_locked: "स्थान लॉक है",
        cal_location_syncing: "GPS सिंक हो रहा है...",

        // Help & Support
        help_subtitle: "हम किसी भी प्रश्न में आपकी सहायता के लिए यहां हैं।",
        help_call: "समर्थन को कॉल करें",
        help_call_desc: "सोम-शुक्र, सुबह 9 से शाम 6 बजे तक",
        help_email: "हमें ईमेल करें",
        help_email_desc: "हम 24 घंटे के भीतर जवाब देते हैं",
        help_faq_title: "अक्सर पूछे जाने वाले प्रश्न",

        faq_q1: "मैं फसल को स्कैन कैसे करूं?",
        faq_a1: "डैशबोर्ड पर जाएं, 'क्रॉप एनालाइज़र' पर क्लिक करें, और अपनी फसल की पत्ती की फोटो अपलोड करें या लें। AI तुरंत इसका विश्लेषण करेगा।",
        faq_q2: "क्या उर्वरक सिफारिश सटीक है?",
        faq_a2: "हम हमेशा महत्वपूर्ण निर्णयों के लिए स्थानीय विशेषज्ञ से परामर्श करने की सलाह देते हैं।",
        faq_q3: "मैं ऐप की भाषा कैसे बदल सकता हूं?",
        faq_a3: "सेटिंग्स > भाषा पर जाएं और अपनी पसंदीदा भाषा (अंग्रेजी, हिंदी या तमिल) चुनें।",
        faq_q4: "अगर ऐप लोड नहीं हो रहा है तो क्या करें?",
        faq_a4: "सेटिंग्स में अंतर्निहित कनेक्शन स्थिति टूल का उपयोग करके अपने इंटरनेट कनेक्शन की जांच करें।",

        // Settings Page
        settings_subtitle: "अपनी प्राथमिकताएं और ऐप कॉन्फ़िगरेशन प्रबंधित करें।",
        settings_language: "भाषा",
        settings_general: "सामान्य प्राथमिकताएं",
        settings_notifications: "पुश सूचनाएं",
        settings_notifications_desc: "मौसम और फसल स्वास्थ्य के बारे में अलर्ट प्राप्त करें।",
        settings_darkmode: "डार्क मोड",
        settings_darkmode_desc: "रात के उपयोग के लिए गहरे रंग की थीम पर स्विच करें।",
        settings_datasaver: "डेटा सेवर",
        settings_datasaver_desc: "मोबाइल डेटा बचाने के लिए छवि गुणवत्ता कम करें।",

        nav_welcome_user: "नमस्ते,",

        // Signup Page
        signup_title: "खाता बनाएं",
        signup_subtitle: "स्मार्ट फार्मिंग समुदाय में शामिल हों",
        signup_name: "पूरा नाम",
        signup_confirm_password: "पासवर्ड की पुष्टि करें",
        signup_btn: "खाता बनाएं",
        signup_have_account: "क्या आपके पास पहले से एक खाता मौजूद है?",
        signup_login: "साइन इन करें",
        signup_creating: "खाता बना रहा है...",

        // Profile Page
        profile_title: "मेरा किसान प्रोफाइल",
        profile_details: "व्यक्तिगत विवरण",
        profile_name: "पूरा नाम",
        profile_email: "ईमेल पता",
        profile_phone: "फ़ोन नंबर",
        profile_location: "खेत का स्थान",
        profile_save: "परिवर्तन सहेजें",
        profile_stat_scans: "कुल स्कैन",
        profile_stat_healthy: "स्वस्थ फसलें",
        profile_stat_issues: "समस्याएं पाई गईं",

        crop_details: "फसल विवरण",
        select_crop: "फसल चुनें",
        district: "ज़िला",
        state: "राज्य",

        // Crops
        crop_rice: "चावल (धान)",
        crop_wheat: "गेहूँ",
        crop_corn: "मक्का",
        crop_potato: "आलू",
        crop_tomato: "टमाटर",
        crop_grape: "अंगूर",
        crop_cashew: "काजू",

        // States
        state_mh: "महाराष्ट्र",
        state_pb: "पंजाब",
        state_ka: "कर्नाटक",
        state_tn: "तमिलनाडु",
        state_up: "उत्तर प्रदेश",
        state_kl: "केरल",

        upload_title: "पत्ती की छवि अपलोड करें",
        upload_subtitle: "अपलोड करने के लिए क्लिक करें",
        use_camera: "कैमरा का उपयोग करें",
        change_photo: "फोटो बदलें",

        analyze_btn: "रोग का विश्लेषण करें",
        analyzing: "विश्लेषण हो रहा है...",
        analyze_another: "दूसरी फसल का विश्लेषण करें",

        ai_diag_title: "एआई-संचालित निदान",
        ai_diag_desc: "तत्काल जानकारी प्राप्त करने के लिए एक फोटो अपलोड करें।",

        feat_visual_title: "दृश्य पहचान",
        feat_visual_desc: "उन्नत मॉडल ब्लाइट, रस्ट और ब्लास्ट जैसी बीमारियों का उच्च सटीकता के साथ पता लगाते हैं।",

        feat_remedy_title: "स्मार्ट उपाय",
        feat_remedy_desc: "अपनी फसल के अनुरूप सटीक उर्वरक खुराक (जैसे हेक्साकोनाज़ोल, ट्राइसाइक्लाज़ोल) प्राप्त करें।",

        feat_alert_title: "स्थानीय अलर्ट",
        feat_alert_desc: "आपके चयनित जिले और वर्तमान मौसम की स्थिति के अनुकूल सिफारिशें।",

        result_condition: "पहचानी गई स्थिति",
        result_confidence: "आत्मविश्वास स्कोर",
        result_low_conf: "कम आत्मविश्वास - मैन्युअल रूप से सत्यापित करें",

        rec_title: "स्मार्ट सिफारिश",
        rec_fertilizer: "उर्वरक",
        rec_dosage: "खुराक",
        rec_instructions: "निर्देश",
        weather_alert: "मौसम की चेतावनी",

        // Diseases
        disease_leaf_blight: "लीफ ब्लाइट (झुलसा रोग)",
        disease_rust: "रस्ट (किट्ट रोग)",
        disease_mosaic: "मोज़ेक वायरस",
        disease_powdery_mildew: "पाउडरी मिल्ड्यू (चूर्णिल आसिता)",
        disease_healthy: "स्वस्थ",
        disease_rice_blast: "राइस ब्लास्ट (झोंका रोग)",
        disease_unknown: "अज्ञात",

        // Recommendations
        rec_leaf_blight_fert: "फंगीसाइड (हेक्साकोनाज़ोल 5% SC)",
        rec_leaf_blight_dose: "2 मिली/लीटर पानी",
        rec_leaf_blight_inst: "तुरंत कवकनाशी का छिड़काव करें। यदि लक्षण बने रहें तो 15 दिनों के बाद दोहराएं। पोटाश डालें।",

        rec_rust_fert: "सल्फर डस्ट / मैनकोज़ेब",
        rec_rust_dose: "25 किग्रा/एकड़ (धूल) या 2.5 ग्राम/लीटर",
        rec_rust_inst: "सुबह-सुबह सल्फर का छिड़काव करें। कवक के प्रसार को रोकने के लिए यूरिया का प्रयोग कम करें।",

        rec_mosaic_fert: "इमिडाक्लोप्रिड (वेक्टर नियंत्रण)",
        rec_mosaic_dose: "100 मिली/एकड़",
        rec_mosaic_inst: "यह एफिड्स द्वारा फैलने वाला एक वायरल रोग है। वाहक को नियंत्रित करें। संक्रमित पौधों को उखाड़ कर नष्ट कर दें।",

        rec_powdery_mildew_fert: "वेटेबल सल्फर / नीम का तेल",
        rec_powdery_mildew_dose: "2 ग्राम/लीटर पानी",
        rec_powdery_mildew_inst: "साप्ताहिक रूप से जैविक नीम के तेल का छिड़काव करें या सल्फर आधारित कवकनाशी का उपयोग करें। हवा का संचार सुधारें।",

        rec_healthy_fert: "जैविक खाद / वर्मीकम्पोस्ट",
        rec_healthy_dose: "500 किग्रा/एकड़",
        rec_healthy_inst: "फसल स्वस्थ है! मिट्टी की सेहत बनाए रखें। नियमित सिंचाई और निगरानी जारी रखें।",

        rec_rice_blast_fert: "ट्राइसाइक्लाज़ोल / इसोप्रोथियोलेन",
        rec_rice_blast_dose: "120 ग्राम/एकड़",
        rec_rice_blast_inst: "चावल के लिए महत्वपूर्ण। ट्राइसाइक्लाज़ोल 75 डब्ल्यूपी का तुरंत प्रयोग करें। धान के खेतों में पानी खड़ा रखें।",

        rec_default_fert: "संतुलित एनपीके (19:19:19)",
        rec_default_dose: "5 किग्रा/एकड़ (छिड़काव)",
        rec_default_inst: "पोषक तत्वों की कमी को दूर करने के लिए छिड़काव करें।",

        disease_cotton_fussarium_wilt: "कपास का उठा रोग (Fusarium Wilt)",
        rec_cotton_fussarium_wilt_fert: "ट्राइकोडर्मा विरिडे / स्यूडोमोनास",
        rec_cotton_fussarium_wilt_dose: "2 किग्रा/एकड़ (मिट्टी में)",
        rec_cotton_fussarium_wilt_inst: "जड़ क्षेत्र को भिगो दें। यदि कवक विल्ट का संदेह है तो सिंचाई तुरंत रोक दें।",

        disease_banana_sigatoka: "केला सिगाटोका (पत्ती धब्बा)",
        rec_banana_sigatoka_fert: "प्रोपिकोनाज़ोल / डिफेनोकोनाज़ोल",
        rec_banana_sigatoka_dose: "1 मिली/लीटर",
        rec_banana_sigatoka_inst: "केले के लिए महत्वपूर्ण। संक्रमित पत्तियों को हटा दें।",

        rec_for: "के लिए",
        rec_in: "में",

        weather_optimal: "उर्वरक आवेदन के लिए अनुकूल परिस्थितियां।",

        // Chatbot
        chat_button: "चैटबॉट",
        chat_title: "किसान सहायक",
        chat_status: "ऑनलाइन",
        chat_placeholder: "फसलों, बीमारियों के बारे में पूछें...",

        // Soil Health
        soil_health: "मिट्टी स्वास्थ्य डेटा",
        soil_advanced: "उन्नत",
        soil_n: "नाइट्रोजन (N)",
        soil_p: "फास्फोरस (P)",
        soil_k: "पोटेशियम (K)",

        // Insights
        insight_title: "लाइव खेती अंतर्दृष्टि",
        insight_weather: "मौसम विजेट",
        insight_market: "बाजार मूल्य",
        insight_per_quintal: "प्रति क्विंटल",
        insight_good_spray: "छिड़काव के लिए अच्छा है",

        // History
        hist_title: "विश्लेषण इतिहास",
        hist_subtitle: "अपने पिछले फसल निदान और सिफारिशों को ट्रैक करें।",
        hist_empty: "कोई इतिहास नहीं मिला। फसल विश्लेषण से शुरू करें!",
        hist_btn_details: "विवरण देखें",
        hist_delete: "रिकॉर्ड हटाएं",

        // Districts - Tamil Nadu
        dist_ariyalur: "अरियालुर",
        dist_chengalpattu: "चेंगलपट्टू",
        dist_chennai: "चेन्नई",
        dist_coimbatore: "कोयंबटूर",
        dist_cuddalore: "कुड्डालोर",
        dist_dharmapuri: "धर्मपुरी",
        dist_dindigul: "डिंडीगुल",
        dist_erode: "इरोड",
        dist_kallakurichi: "कल्लाकुरिची",
        dist_kancheepuram: "कांचीपुरम",
        dist_kanniyakumari: "कन्याकुमारी",
        dist_karur: "करूर",
        dist_krishnagiri: "कृष्णगिरि",
        dist_madurai: "मदुरै",
        dist_mayiladuthurai: "मयिलादुथुराई",
        dist_nagapattinam: "नागापट्टिनम",
        dist_namakkal: "नामक्कल",
        dist_nilgiris: "नीलगिरी",
        dist_perambalur: "पेराम्बलुर",
        dist_pudukkottai: "पुदुक्कोट्टई",
        dist_ramanathapuram: "रामनाथपुरम",
        dist_ranipet: "रानीपेट",
        dist_salem: "सलेम",
        dist_sivagangai: "शिवगंगा",
        dist_tenkasi: "तेनकासी",
        dist_thanjavur: "तंजावुर",
        dist_theni: "थेनी",
        dist_thiruvallur: "तिरुवल्लूर",
        dist_thiruvarur: "तिरुवारुर",
        dist_thoothukudi: "थूथुकुडी",
        dist_tiruchirappalli: "तिरुचिरापल्ली",
        dist_tirunelveli: "तिरुनेलवेली",
        dist_tirupathur: "तिरूपथुर",
        dist_tiruppur: "तिरुपूर",
        dist_tiruvannamalai: "तिरुवन्नामलई",
        dist_vellore: "वेल्लोर",
        dist_viluppuram: "विलुप्पुरम",
        dist_virudhunagar: "विरुद्धनगर",

        // Districts - Maharashtra
        dist_pune: "पुणे",
        dist_nagpur: "नागपुर",
        dist_nashik: "नाशिक",
        dist_mumbai_city: "मुंबई सिटी",
        dist_mumbai_suburban: "मुंबई उपनगर",
        dist_ahmednagar: "अहमदनगर",
        dist_aurangabad: "औरंगाबाद",

        // Districts - Punjab
        dist_amritsar: "अमृतसर",
        dist_ludhiana: "लुधियाना",
        dist_jalandhar: "जालंधर",
        dist_patiala: "पटियाला",
        dist_mohali_sas_nagar: "मोहाली",

        // Districts - Karnataka
        dist_bangalore_urban: "बेंगलुरु शहरी",
        dist_mysore: "मैसूर",
        dist_belgaum: "बेलगाम",
        dist_mangalore: "मंगलौर",

        // Districts - Kerala
        dist_wayanad: "वायनाड",
        dist_idukki: "इडुक्की",
        dist_alappuzha: "अलाप्पुझा",

        // Districts - Uttar Pradesh
        dist_lucknow: "लखनऊ",
        dist_varanasi: "वाराणसी",
        dist_agra: "आगरा",
        dist_kanpur_nagar: "कानपुर"
    },
    TA: {
        nav_analyze: "பயிர் பகுப்பாய்வு",
        nav_history: "எனது வரலாறு",
        nav_signin: "உள்நுழைய",

        hero_title_1: "ஸ்மார்ட் விவசாய",
        hero_title_2: "புரட்சி",
        hero_subtitle: "AI மூலம் பயிர் நோய்களை உடனடியாகக் கண்டறிந்து, உங்கள் மண்ணுக்கு ஏற்ற உரப் பரிந்துரைகளைப் பெறுங்கள்.",
        footer: "© 2026 அக்ரிக்யூர் AI அமைப்புகள். இந்திய விவசாயிகளுக்காக உருவாக்கப்பட்டது.",

        // Login Page
        login_welcome: "மீண்டும் வருக",
        login_subtitle: "உங்கள் பண்ணை டாஷ்போர்டை அணுக உள்நுழையவும்",
        login_email: "மின்னஞ்சல் முகவரி",
        login_password: "கடவுச்சொல்",
        login_btn: "உள்நுழைய",
        login_forgot: "கடவுச்சொல் மறந்துவிட்டதா?",
        login_no_account: "கணக்கு இல்லையா?",
        login_signup: "பதிவு செய்க",
        login_logging_in: "உள்நுழைகிறது...",
        nav_logout: "வெளியேறு",
        nav_profile: "என் சுயவிவரம்",
        nav_dashboard: "டாஷ்போர்டு",
        nav_settings: "அமைப்புகள்",
        nav_help: "உதவி & ஆதரவு",
        nav_alerts: "வானிலை எச்சரிக்கைகள்",
        nav_tools: "கருவிகள்",
        nav_simulators: "உருவகப்படுத்துதல்கள்",
        nav_farmer_tools: "விவசாயி கருவிகள்",
        nav_advanced_sims: "மேம்பட்ட உருவகப்படுத்துதல்கள்",
        nav_crop_calendar: "பயிர் காலண்டர்",
        nav_fert_calc: "உரக் கால்குலேட்டர்",
        nav_weather_forecast: "வானிலை முன்னறிவிப்பு",
        nav_market_prices: "சந்தை விலைகள்",
        nav_soil_health: "மண் ஆரோக்கிய பரிசோதனை",
        nav_impact_sim: "தாக்க உருவகப்படுத்தி",
        nav_future_growth: "எதிர்கால வளர்ச்சி உருவகப்படுத்தி",
        nav_disease_spread: "நோய் பரவல் உருவகப்படுத்தி",
        nav_farming_timeline: "விவசாய காலவரிசை",

        soil_alluvial: "வண்டல் மண்",
        soil_red_soil: "செம்மண்",
        soil_black_soil: "கரிசல் மண்",
        soil_laterite: "லேட்டரைட் மண்",
        soil_desert_soil: "பாலைவன மண்",

        // Impact Simulator
        impact_title: "தாக்கசிம்",
        impact_subtitle: "கரிம மற்றும் இரசாயன விவசாய விளைவுகளை ஒப்பிடுக",
        impact_parameters: "அளவுருக்கள்",
        impact_target_crop: "இலக்கு பயிர்",
        impact_soil_profile: "மண் விவரம்",
        impact_area: "பகுதி (ஏக்கர்)",
        impact_cycle: "சுழற்சி (மாதம்)",
        impact_intensity: "உள்ளீடு அடர்த்தி",
        impact_low: "குறைந்த",
        impact_medium: "நடுத்தர",
        impact_high: "அதிக",
        impact_run_sim: "உருவகப்படுத்துதலை இயக்கவும்",
        impact_simulating: "உருவகப்படுத்துகிறது...",
        impact_organic_protocol: "கரிம நெறிமுறை",
        impact_safe_yield: "பாதுகாப்பான மகசூல்",
        impact_chemical_protocol: "இரசாயன நெறிமுறை",
        impact_high_risk: "அதிக ஆபத்து",
        impact_est_yield: "மதிப்பிடப்பட்ட மகசூல்",
        impact_proj_profit: "மதிப்பிடப்பட்ட லாபம்",
        impact_soil_health: "மண் ஆரோக்கியம்",
        impact_yield_journey: "மகசூல் கணிப்பு பயணம்",
        impact_ai_insight: "AI அதிகாரப்பூர்வ நுண்ணறிவு",
        impact_listen: "கேளுங்கள்",
        impact_stop: "நிறுத்துங்கள்",
        impact_ws_title: "தாக்க பகுப்பாய்வு பணியிடம்",
        impact_ws_awaiting: "உள்ளமைவுக்காக காத்திருக்கிறது",
        impact_ws_ready: "உருவகப்படுத்துதலுக்கு தயார்",
        impact_ws_desc: "கரிம மற்றும் இரசாயன விளைவுகளை ஒப்பிட இடது பலகத்தில் பயிர் மற்றும் விவசாய அளவுருக்களை சரிசெய்யவும்.",
        impact_ws_step1: "உள்ளீடுகள்",
        impact_ws_step1_desc: "பயிர் மற்றும் பகுதியை அமைக்கவும்",
        impact_ws_step2: "உருவகப்படுத்து",
        impact_ws_step2_desc: "AI மாதிரி இயக்கு",
        impact_ws_step3: "ஒப்பிடுக",
        impact_ws_step3_desc: "மகசூலை மதிப்பாய்வு சேய்",

        // Smart Farming Timeline
        timeline_title: "ஸ்மார்ட் விவசாய காலவரிசை",
        timeline_subtitle: "AI-உருவாக்கப்பட்ட சாகுபடி அட்டவணை & மைல்கற்கள்",
        timeline_parameters: "சாகுபடி விவரங்கள்",
        timeline_generate_btn: "காலவரிசையை உருவாக்கு",
        timeline_preview_title: "காலவரிசை முன்னோட்டம்",
        timeline_preview_placeholder: "சாகுபடி அட்டவணையை முன்னோட்டம் காண விவரங்களை உள்ளிடவும்",
        timeline_crop: "பயிர் இனங்கள்",
        timeline_start_date: "விதைப்பு தேதி",
        timeline_deployment_params: "பயன்பாட்டு அளவுருக்கள்",
        timeline_active_phase: "செயலில் உள்ள நிலை",
        timeline_pathogen_alert: "நோய் கிருமி எச்சரிக்கை",
        timeline_critical_risk: "முக்கிய அபாயம்: மண் சிகிச்சை",
        timeline_economic_insight: "பொருளாதார நுண்ணறிவு",
        timeline_yield_confidence: "மகசூல் நம்பிக்கை",
        timeline_water_intensity: "நீர் செறிவை",

        // Crop Calendar
        cal_badge: "AI துல்லிய திட்டமிடுபவர்",
        cal_title: "பயிர் காலண்டர்",
        cal_subtitle: "நேரடி வானிலை, மண் மற்றும் சந்தை நுண்ணறிவுடன் AI-இயக்கப்படும் வாழ்க்கைச் சுழற்சி திட்டமிடுபவர்.",
        cal_search_placeholder: "எந்த பயிரையும் தேடுங்கள்... (எ.கா. நெல், தக்காளி, நெ...)",
        cal_search_label: "பயிர் தேடுக",
        cal_date_label: "விதைப்பு தேதி",
        cal_location_label: "இடம்",
        cal_location_detecting: "இடத்தை கண்டறிகிறது...",
        cal_location_edit: "இடத்தை திருத்து",
        cal_location_hide: "மறை",
        cal_state_placeholder: "மாநிலம் (எ.கா. தமிழ்நாடு)",
        cal_district_placeholder: "மாவட்டம் (எ.கா. மதுரை)",
        cal_generate_btn: "AI காலண்டர் உருவாக்கு",
        cal_generating: "AI உங்கள் காலண்டரை உருவாக்குகிறது...",
        cal_empty_title: "உங்கள் பருவத்தை திட்டமிட தயார்",
        cal_empty_desc: "முழுமையான AI-இயக்கப்படும் விவசாய காலண்டரைப் பெற பயிரை தேடி விதைப்பு தேதியை அமைக்கவும்.",
        cal_step1: "பயிர் தேடுக",
        cal_step1_desc: "எந்த பயிர் பெயரையும் தட்டச்சு செய்யவும்",
        cal_step2: "தேதி அமை",
        cal_step2_desc: "விதைப்பு தேதியை தேர்ந்தெடுக்கவும்",
        cal_step3: "காலண்டர் பெறுக",
        cal_step3_desc: "AI உங்கள் திட்டத்தை உருவாக்கும்",
        cal_yield_conf: "மகசூல் நம்பிக்கை",
        cal_water: "நீர் செறிவு",
        cal_season: "பருவம்",
        cal_duration: "காலம்",
        cal_days: "நாட்கள்",
        cal_harvest_window: "அறுவடை சாளரம்",
        cal_early: "முன்னதாக",
        cal_optimal: "சிறந்த நேரம்",
        cal_late: "தாமதமாக",
        cal_soil_req: "மண் தேவைகள்",
        cal_market: "சந்தை கண்ணோட்டம்",
        cal_warnings: "முக்கிய எச்சரிக்கைகள்",
        cal_ai_summary: "AI நிபுணர் சுருக்கம்",
        cal_active_phase: "செயலில் உள்ள நிலை",
        cal_weather_adj: "வானிலை ஆலோசனை",
        cal_irrigation: "நீர்ப்பாசனம்",
        cal_fertilizer: "உரம்",
        cal_pest_risk: "பூச்சி / நோய் அபாயம்",
        cal_economic: "பொருளாதார நுண்ணறிவு",
        cal_risk_high: "அதிக அபாயம்",
        cal_risk_medium: "நடுத்தர அபாயம்",
        cal_risk_low: "குறைந்த அபாயம்",
        cal_no_results: "பயிர் எதுவும் கிடைக்கவில்லை. வேறு பெயரை முயற்சிக்கவும்.",
        cal_ai_searching: "AI தேடுகிறது...",
        cal_location_locked: "இடம் பூட்டப்பட்டது",
        cal_location_syncing: "GPS ஒத்திசைக்கிறது...",

        // Help & Support
        help_subtitle: "எந்தவொரு கேள்விக்கும் உங்களுக்கு உதவ நாங்கள் இருக்கிறோம்.",
        help_call: "ஆதரவை அழைக்கவும்",
        help_call_desc: "திங்கள்-வெள்ளி, காலை 9 - மாலை 6",
        help_email: "எங்களுக்கு மின்னஞ்சல் செய்யவும்",
        help_email_desc: "நாங்கள் 24 மணி நேரத்திற்குள் பதிலளிக்கிறோம்",
        help_faq_title: "அடிக்கடி கேட்கப்படும் கேள்விகள்",

        faq_q1: "நான் ஒரு பயிரை ஸ்கேன் செய்வது எப்படி?",
        faq_a1: "டாஷ்போர்டுக்குச் சென்று, 'பயிர் பகுப்பாய்வி' என்பதைக் கிளிக் செய்து, உங்கள் பயிர் இலையின் புகைப்படத்தைப் பதிவேற்றவும்.",
        faq_q2: "உர பரிந்துரை துல்லியமானதா?",
        faq_a2: "முக்கியமான முடிவுகளுக்கு உள்ளூர் நிபுணரை அணுகுமாறு நாங்கள் எப்போதும் பரிந்துரைக்கிறோம்.",
        faq_q3: "பயன்பாட்டு மொழியை நான் எவ்வாறு மாற்றுவது?",
        faq_a3: "அமைப்புகள் > மொழி என்பதற்குச் சென்று உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.",
        faq_q4: "பயன்பாடு ஏற்றப்படவில்லை என்றால் என்ன செய்வது?",
        faq_a4: "அமைப்புகளில் உள்ள இணைப்பு நிலை கருவியைப் பயன்படுத்தி உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும்.",

        // Settings Page
        settings_subtitle: "உங்கள் விருப்பங்களையும் பயன்பாட்டு அமைப்புகளையும் நிர்வகிக்கவும்.",
        settings_language: "மொழி",
        settings_general: "பொதுவான விருப்பங்கள்",
        settings_notifications: "அறிவிப்புகள்",
        settings_notifications_desc: "வானிலை மற்றும் பயிர் ஆரோக்கியம் பற்றிய எச்சரிக்கைகளைப் பெறுங்கள்.",
        settings_darkmode: "டார்க் பயன்முறை",
        settings_darkmode_desc: "இரவு உபயோகத்திற்கு இருண்ட தீம்-க்கு மாற்றவும்.",
        settings_datasaver: "டேட்டா சேவர்",
        settings_datasaver_desc: "மொபைல் டேட்டாவைச் சேமிக்க படத் தரத்தைக் குறைக்கவும்.",

        nav_welcome_user: "வணக்கம்,",

        // Signup Page
        signup_title: "கணக்கை உருவாக்கவும்",
        signup_subtitle: "ஸ்மார்ட் விவசாய சமூகத்தில் சேரவும்",
        signup_name: "முழு பெயர்",
        signup_confirm_password: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
        signup_btn: "கணக்கை உருவாக்கவும்",
        signup_have_account: "ஏற்கனவே கணக்கு உள்ளதா?",
        signup_login: "உள்நுழைய",
        signup_creating: "கணக்கை உருவாக்குகிறது...",

        // Profile Page
        profile_title: "என் விவசாயி சுயவிவரம்",
        profile_details: "தனிப்பட்ட விவரங்கள்",
        profile_name: "முழு பெயர்",
        profile_email: "மின்னஞ்சல் முகவரி",
        profile_phone: "தொலைபேசி எண்",
        profile_location: "பண்ணை இடம்",
        profile_save: "மாற்றங்களை சேமிக்கவும்",
        profile_stat_scans: "மொத்த ஸ்கேன்",
        profile_stat_healthy: "ஆரோக்கியமான பயிர்கள்",
        profile_stat_issues: "கண்டறியப்பட்ட சிக்கல்கள்",

        crop_details: "பயிர் விவரங்கள்",
        select_crop: "பயிரைத் தேர்ந்தெடுக்கவும்",
        district: "மாவட்டம்",
        state: "மாநிலம்",

        // Crops
        crop_rice: "அரிசி (நெல்)",
        crop_wheat: "கோதுமை",
        crop_corn: "சோளம்",
        crop_potato: "உருளைக்கிழங்கு",
        crop_tomato: "தக்காளி",
        crop_grape: "திராட்சை",
        crop_cashew: "முந்திரி",

        // States
        state_mh: "மகாராஷ்டிரா",
        state_pb: "பஞ்சாப்",
        state_ka: "கர்நாடகா",
        state_tn: "தமிழ்நாடு",
        state_up: "உத்திர பிரதேசம்",
        state_kl: "கேரளா",

        upload_title: "இலை படத்தை பதிவேற்றவும்",
        upload_subtitle: "பதிவேற்ற கிளிக் செய்யவும்",
        use_camera: "கேமராவைப் பயன்படுத்தவும்",
        change_photo: "புகைப்படத்தை மாற்றவும்",

        analyze_btn: "நோயை பகுப்பாய்வு செய்யவும்",
        analyzing: "பகுப்பாய்வு செய்கிறது...",
        analyze_another: "மற்றொரு பயிரை பகுப்பாய்வு செய்",

        ai_diag_title: "AI-இயக்கப்படும் நோய் கண்டறிதல்",
        ai_diag_desc: "உடனடித் தகவலைப் பெற புகைப்படத்தைப் பதிவேற்றவும்.",

        feat_visual_title: "காட்சி அங்கீகாரம்",
        feat_visual_desc: "மேம்பட்ட மாதிரிகள் ப்ளைட், ரஸ்ட் மற்றும் பிளாஸ்ட் போன்ற நோய்களை அதிக துல்லியத்துடன் கண்டறிகின்றன.",

        feat_remedy_title: "ஸ்மார்ட் தீர்வுகள்",
        feat_remedy_desc: "உங்கள் பயிருக்கு ஏற்ற துல்லியமான உர அளவுகளை (எ.கா. ஹெக்சாகோனசோல், ட்ரைசைக்லசோல்) பெறுங்கள்.",

        feat_alert_title: "உள்ளூர் எச்சரிக்கைகள்",
        feat_alert_desc: "உங்கள் தேர்ந்தெடுக்கப்பட்ட மாவட்டம் மற்றும் தற்போதைய வானிலைக்கு ஏற்ற பரிந்துரைகள்.",

        result_condition: "கண்டறியப்பட்ட நிலை",
        result_confidence: "நம்பிக்கை மதிப்பெண்",
        result_low_conf: "குறைந்த நம்பிக்கை - கைமுறையாக சரிபார்க்கவும்",

        rec_title: "ஸ்மார்ட் பரிந்துரை",
        rec_fertilizer: "உரம்",
        rec_dosage: "அளவு",
        rec_instructions: "வழிமுறைகள்",
        weather_alert: "வானிலை எச்சரிக்கை",

        // Diseases
        disease_leaf_blight: "இலை கருகல் நோய் (Leaf Blight)",
        disease_rust: "துரு நோய் (Rust)",
        disease_mosaic: "மொசைக் வைரஸ்",
        disease_powdery_mildew: "சாம்பல் நோய் (Powdery Mildew)",
        disease_healthy: "ஆரோக்கியமான",
        disease_rice_blast: "நெல் குலை நோய் (Rice Blast)",
        disease_unknown: "தெரியாத நோய்",

        // Recommendations
        rec_leaf_blight_fert: "பூஞ்சையாக்கிகள் (ஹெக்சாகோனசோல் 5% SC)",
        rec_leaf_blight_dose: "2 மிலி/லிட்டர் தண்ணீர்",
        rec_leaf_blight_inst: "பூஞ்சைக் கொல்லியை உடனடியாக தெளிக்கவும். அறிகுறிகள் தொடர்ந்தால் 15 நாட்களுக்குப் பிறகு மீண்டும் செய்யவும். பொட்டாஷ் சேர்க்கவும்.",

        rec_rust_fert: "சல்பர் டஸ்ட் / மான்கோசெப்",
        rec_rust_dose: "25 கிலோ/ஏக்கர் (தூள்) அல்லது 2.5 கிராம்/லிட்டர்",
        rec_rust_inst: "அதிகாலையில் கந்தகத்தை தூவி விடவும். பூஞ்சை பரவுவதைத் தடுக்க யூரியா பயன்பாட்டைக் குறைக்கவும்.",

        rec_mosaic_fert: "இimidacloprid (திசையன் கட்டுப்பாடு)",
        rec_mosaic_dose: "100 மிலி / ஏக்கர்",
        rec_mosaic_inst: "இது அசுவினி மூலம் பரவும் வைரஸ் நோய். பரப்பும் பூச்சிகளை கட்டுப்படுத்தவும். பாதிக்கப்பட்ட செடிகளை பிடுங்கி அழிக்கவும்.",

        rec_powdery_mildew_fert: "வெட்டபிள் சல்பர் / வேப்ப எண்ணெய்",
        rec_powdery_mildew_dose: "2 கிராம்/லிட்டர் தண்ணீர்",
        rec_powdery_mildew_inst: "வாரந்தோறும் ஆர்கானிக் வேப்ப எண்ணெயைத் தெளிக்கவும் அல்லது சல்பர் சார்ந்த பூஞ்சைக் கொல்லிகளைப் பயன்படுத்தவும். காற்று சுழற்சியை மேம்படுத்தவும்.",

        rec_healthy_fert: "ஆர்கானிக் உரம் / மண்புழு உரம்",
        rec_healthy_dose: "500 கிலோ/ஏக்கர்",
        rec_healthy_inst: "பயிர் ஆரோக்கியமாக உள்ளது! மண் வளத்தை பராமரிக்கவும். வழக்கமான நீர்ப்பாசனம் மற்றும் கண்காணிப்பைத் தொடரவும்.",

        rec_rice_blast_fert: "ட்ரைசைக்லசோல் / ஐசோப்ரோதியோலேன்",
        rec_rice_blast_dose: "120 கிராம்/ஏக்கர்",
        rec_rice_blast_inst: "அரிசிக்கு முக்கியமானது. ட்ரைசைக்லசோல் 75 WP-ஐ உடனடியாகப் பயன்படுத்தவும். நெல் வயல்களில் தண்ணீர் தேங்கி நிற்கச் செய்யவும்.",

        rec_default_fert: "சமச்சீர் NPK (19:19:19)",
        rec_default_dose: "5 கிலோ/ஏக்கர் (இலை வழி)",
        rec_default_inst: "பொதுவான ஊட்டச்சத்து குறைபாடுகளைத் தீர்க்க தெளிக்கவும்.",

        disease_cotton_fussarium_wilt: "பருத்தி வாடல் நோய்",
        rec_cotton_fussarium_wilt_fert: "ட்ரைக்கோடெர்மா விரிடி / சூடோமோனாஸ்",
        rec_cotton_fussarium_wilt_dose: "2 கிலோ/ஏக்கர் (மண்ணில்)",
        rec_cotton_fussarium_wilt_inst: "வேர் பகுதியை நனைக்கவும். பூஞ்சை வாடல் சந்தேகம் இருந்தால் உடனடியாக நீர்ப்பாசனத்தை நிறுத்தவும்.",

        disease_banana_sigatoka: "वाழை सிகடோகா (இலை புள்ளி)",
        rec_banana_sigatoka_fert: "புரோபிகோனசோல் / டிஃபெனோகனசோல்",
        rec_banana_sigatoka_dose: "1 மிலி/லிட்டர்",
        rec_banana_sigatoka_inst: "பாதிக்கப்பட்ட இலைகளை அகற்றவும்.",

        disease_banana_cordana: "वाழை கோர்டானா இலை புள்ளி (Cordana Leaf Spot)",
        rec_banana_cordana_fert: "காப்பர் ஆக்ஸிகுளோரைடு / மான்கோசெப்",
        rec_banana_cordana_dose: "2.5 கிராம்/லிட்டர்",
        rec_banana_cordana_inst: "பாதிக்கப்பட்ட இலைகளை அகற்றவும். நீர் வடிகாலினை மேம்படுத்தவும்.",

        disease_banana_pestalotiopsis: "வாழை பெஸ்டலோடியோப்ஸிஸ்",
        rec_banana_pestalotiopsis_fert: "கார்பென்டாசிம் / தியோபனேட் மெத்தில்",
        rec_banana_pestalotiopsis_dose: "1 கிராம்/லிட்டர்",
        rec_banana_pestalotiopsis_inst: "நோய்த்தொற்று தீவிரமாக இருந்தால் பூஞ்சைக் கொல்லிகளைத் தெளிக்கவும்.",

        disease_banana_healthy: "ஆரோக்கியமான வாழை",
        rec_banana_healthy_fert: "இயற்கை உரம் / மண்புழு உரம்",
        rec_banana_healthy_dose: "2 கிலோ/செடி",
        rec_banana_healthy_inst: "பயிர் ஆரோக்கியமாக உள்ளது! வழக்கமான நீர்ப்பாசனத்தைத் தொடரவும்.",

        rec_for: "பயிருக்கு",
        rec_in: "பகுதியில்",

        weather_optimal: "உரம் பயன்பாட்டிற்கு உகந்த நிலைமைகள்.",

        // Chatbot
        chat_button: "சாட்போட்",
        chat_title: "விவசாய உதவியாளர்",
        chat_status: "ஆன்லைன்",
        chat_placeholder: "பயிர்கள், நோய்கள் பற்றி கேளுங்கள்...",

        // Soil Health
        soil_health: "மண் ஆரோக்கியத் தரவு",
        soil_advanced: "மேம்பட்ட",
        soil_n: "நைட்ரஜன் (N)",
        soil_p: "பாஸ்பரஸ் (P)",
        soil_k: "பொட்டாசியம் (K)",

        // Insights
        insight_title: "நேரடி விவசாய நுண்ணறிவு",
        insight_weather: "வானிலை அறிவிப்பு",
        insight_market: "சந்தை விலை",
        insight_per_quintal: "ஒரு குவிண்டாலுக்கு",
        insight_good_spray: "மருந்து தெளிக்க ஏற்றது",

        // History
        hist_title: "பகுப்பாய்வு வரலாறு",
        hist_subtitle: "உங்கள் கடந்தகால பயிர் நோய் கண்டறிதல் மற்றும் பரிந்துரைகளைக் கண்காணிக்கவும்.",
        hist_empty: "வரலாறு எதுவும் இல்லை. ஒரு பயிரை பகுப்பாய்வு செய்வதன் மூலம் தொடங்கவும்!",
        hist_btn_details: "விவரங்களைக் காண்க",
        hist_delete: "பதிவை நீக்கு",

        // Districts - Tamil Nadu
        dist_ariyalur: "அரியலூர்",
        dist_chengalpattu: "செங்கல்பட்டு",
        dist_chennai: "சென்னை",
        dist_coimbatore: "கோயம்புத்தூர்",
        dist_cuddalore: "கடலூர்",
        dist_dharmapuri: "தர்மபுரி",
        dist_dindigul: "திண்டுக்கல்",
        dist_erode: "ஈரோடு",
        dist_kallakurichi: "கள்ளக்குறிச்சி",
        dist_kancheepuram: "காஞ்சிபுரம்",
        dist_kanniyakumari: "கன்னியாகுமரி",
        dist_karur: "கரூர்",
        dist_krishnagiri: "கிருஷ்ணகிரி",
        dist_madurai: "மதுரை",
        dist_mayiladuthurai: "மயிலாடுதுறை",
        dist_nagapattinam: "நாகப்பட்டினம்",
        dist_namakkal: "நாமக்கல்",
        dist_nilgiris: "நீலகிரி",
        dist_perambalur: "பெரம்பலூர்",
        dist_pudukkottai: "புதுக்கோட்டை",
        dist_ramanathapuram: "இராமநாதபுரம்",
        dist_ranipet: "ராணிப்பேட்டை",
        dist_salem: "சேலம்",
        dist_sivagangai: "சிவகாசி",
        dist_tenkasi: "தென்காசி",
        dist_thanjavur: "தஞ்சாவூர்",
        dist_theni: "தேனி",
        dist_thiruvallur: "திருவள்ளூர்",
        dist_thiruvarur: "திருவாரூர்",
        dist_thoothukudi: "தூத்துக்குடி",
        dist_tiruchirappalli: "திருச்சிராப்பள்ளி",
        dist_tirunelveli: "திருநெல்வேலி",
        dist_tirupathur: "திருப்பத்தூர்",
        dist_tiruppur: "திருப்பூர்",
        dist_tiruvannamalai: "திருவண்ணாமலை",
        dist_vellore: "வேலூர்",
        dist_viluppuram: "விழுப்புரம்",
        dist_virudhunagar: "விருதுநகர்",

        // Districts - Maharashtra
        dist_pune: "புனே",
        dist_nagpur: "நாக்பூர்",
        dist_nashik: "நாசிக்",
        dist_mumbai_city: "மும்பை சிட்டி",
        dist_mumbai_suburban: "மும்பை புறநகர்",
        dist_ahmednagar: "அகமதுநகர்",
        dist_aurangabad: "அவுரங்காபாத்",

        // Districts - Punjab
        dist_amritsar: "அமிர்தசரஸ்",
        dist_ludhiana: "லூதியானா",
        dist_jalandhar: "ஜலந்தர்",
        dist_patiala: "பாட்டியாலா",
        dist_mohali_sas_nagar: "மொஹாலி",

        // Districts - Karnataka
        dist_bangalore_urban: "பெங்களூரு நகர்ப்புறம்",
        dist_mysore: "மைசூர்",
        dist_belgaum: "பெல்காம்",
        dist_mangalore: "மங்களூர்",

        // Districts - Kerala
        dist_wayanad: "வயநாடு",
        dist_idukki: "இடுக்கி",
        dist_alappuzha: "ஆலப்புழா",

        // Districts - Uttar Pradesh
        dist_lucknow: "லக்னோ",
        dist_varanasi: "வாரணாசி",
        dist_agra: "ஆக்ரா",
        dist_kanpur_nagar: "கான்பூர்"
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = React.useState(() => {
        return localStorage.getItem('agriaid_lang') || 'EN';
    });

    const changeLanguage = (lang) => {
        setLanguage(lang);
        localStorage.setItem('agriaid_lang', lang);
    };

    const t = (key) => {
        return translations[language]?.[key] || translations['EN'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
